{
 "title": "py_product",
 "time": { "from": "2023-01-12T00:00:00.000Z", "to": "2024-01-01T00:00:00.000Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Cost Service",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " \r\n SELECT \r\n date as \"time\" ,\r\nTotalcosts as yellow_Cost \r\nFROM\r\n  py_product\r\nwhere\r\n source = 'yellow'"
    },
    {
     "rawSql": "  SELECT \r\n date as \"time\" ,\r\nTotalcosts as purple_Cost\r\nFROM\r\n  py_product\r\nwhere\r\n source = 'purple'"
    }
   ]
  },
  {
   "title": "Recent Data(TotalCost prodc)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "\r\nselect \r\nCAST(ps.date AS TEXT),\r\nps.Totalcosts as Purple,\r\nys.Totalcosts as Yellow\r\nfrom (\r\nselect\r\n  *\r\nFROM\r\n  py_product\r\nwhere\r\n  source = 'yellow'\r\n) ys \r\ninner join \r\n\r\n(\r\nselect\r\n  *\r\nFROM\r\n  py_product\r\nwhere\r\n  source = 'purple'\r\n) ps\r\non ps.date=ys.date\r\nOrder \r\n by ps.date desc\r\nLimit 2"
    }
   ]
  },
  {
   "title": "purple_product_latest two_months_data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select\r\n  date  as \"time\",\r\n  Capabilities,\r\n\tIcapabilities,\r\n\tAPI,\r\n\tUI,\r\n\tExAPI,\r\n\tPerformances,\r\n\tBcapabilities,\r\n\tCCTV,\r\n\tTotalcosts,\r\n\tProductTrial,\r\n\tProductCapabilities\r\nFROM\r\n  py_product\r\nwhere\r\n  source = 'purple'\r\nOrder \r\n by date desc\r\nLimit 2\r\n"
    }
   ]
  },
  {
   "title": "Capabilites MonthWise",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "\r\nselect \r\nCAST(ps.date AS TEXT),\r\nps.Capabilities as purple_Capabilities,\r\nys.Capabilities as yellow_Capabilities\r\nfrom (\r\nselect\r\n  *\r\nFROM\r\n  py_product\r\nwhere\r\n  source = 'yellow'\r\n) ys \r\ninner join \r\n\r\n(\r\nselect\r\n *\r\nFROM\r\n  py_product\r\nwhere\r\n  source = 'purple'\r\n) ps\r\non ps.date=ys.date"
    }
   ]
  },
  {
   "title": "yellow_product_latest two_months_data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select\r\n  date  as \"time\",\r\n \r\n Capabilities,\r\n\tIcapabilities,\r\n\tAPI,\r\n\tUI,\r\n\tExAPI,\r\n\tPerformances,\r\n\tBcapabilities,\r\n\tCCTV,\r\n\tTotalcosts,\r\n\tProductTrial,\r\n\tProductCapabilities\r\n\t\r\nFROM\r\n  py_product\r\nwhere\r\n  source = 'yellow'\r\nOrder \r\n by date desc\r\nLimit 2\r\n"
    }
   ]
  }
 ]
}