{
 "title": "py_service_1",
 "time": { "from": "2021-01-01T00:00:00.000Z", "to": "2024-12-31T00:00:00.000Z" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": " \r\n SELECT \r\n date as \"time\" ,\r\nTotalcosts as yellow_Cost \r\nFROM\r\n  py_servcie\r\nwhere\r\n source = 'yellow'"
    },
    {
     "rawSql": "  SELECT \r\n date as \"time\" ,\r\nTotalcosts as purple_Cost\r\nFROM\r\n  py_servcie\r\nwhere\r\n source = 'purple'"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " \r\n SELECT \r\n date as \"time\" ,\r\nTotalcosts as yellow_Cost \r\nFROM\r\n  py_servcie\r\nwhere\r\n source = 'yellow'"
    },
    {
     "rawSql": "  SELECT \r\n date as \"time\" ,\r\nTotalcosts as purple_Cost\r\nFROM\r\n  py_servcie\r\nwhere\r\n source = 'purple'"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select \r\nps.date as \"time\" ,\r\nps.Totalcosts as purple_Cost\r\nfrom (SELECT *\r\nFROM\r\n  py_servcie\r\nwhere\r\n source = 'purple') ps \r\n inner join\r\n (SELECT * \r\nFROM\r\n  py_servcie\r\nwhere\r\n source = 'yellow') ys \r\n \r\n on ps.date =ys.date"
    },
    {
     "rawSql": "select \r\nps.date as \"time\" ,\r\nys.Totalcosts as yellow_Cost \r\nfrom (SELECT *\r\nFROM\r\n  py_servcie\r\nwhere\r\n source = 'purple') ps \r\n inner join\r\n (SELECT * \r\nFROM\r\n  py_servcie\r\nwhere\r\n source = 'yellow') ys \r\n \r\n on ps.date =ys.date"
    }
   ]
  },
  {
   "title": "Total Cost Service",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " \r\n SELECT \r\n date as \"time\" ,\r\nTotalcosts as yellow_Cost \r\nFROM\r\n  py_servcie\r\nwhere\r\n source = 'yellow'"
    },
    {
     "rawSql": "  SELECT \r\n date as \"time\" ,\r\nTotalcosts as purple_Cost\r\nFROM\r\n  py_servcie\r\nwhere\r\n source = 'purple'"
    }
   ]
  },
  {
   "title": "CapabilitiesService",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "\r\n select \r\nCAST(ps.date AS TEXT),\r\nps.CapabilitiesService as purple_CapabilitiesService,\r\nys.CapabilitiesService as yellow_CapabilitiesService \r\nfrom (SELECT *\r\nFROM\r\n  py_servcie\r\nwhere\r\n source = 'purple') ps \r\n inner join\r\n (SELECT * \r\nFROM\r\n  py_servcie\r\nwhere\r\n source = 'yellow') ys  \r\n on ps.date =ys.date;"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " SELECT \r\n date as \"time\" ,\r\nTotalcosts as yellow_Cost \r\nFROM\r\n  py_servcie\r\nwhere\r\n source = 'yellow'"
    },
    {
     "rawSql": " SELECT \r\n date as \"time\" ,\r\nTotalcosts as purple_Cost\r\nFROM\r\n  py_servcie\r\nwhere\r\n source = 'purple'"
    }
   ]
  },
  {
   "title": "yellow account service data.",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "select \r\n CAST(date AS TEXT),\r\n CapabilitiesService,\r\n Icapabilities,\r\n APIService,\r\n UIService\r\n \r\n FROM\r\n  py_servcie\r\n  where\r\n source = 'yellow'"
    }
   ]
  },
  {
   "title": "Capabilites year wise",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": " select \r\nDATE_PART('Year', date) AS yearWise,\r\nsum(CapabilitiesService) as sum,\r\navg(CapabilitiesService) as avg,\r\nmin(CapabilitiesService) as min,\r\nmax(CapabilitiesService) as max\r\n\r\nFROM\r\n  py_servcie\r\n  where\r\n source = 'yellow'\r\n GROUP BY DATE_PART('Year', date);"
    }
   ]
  },
  {
   "title": "Recent Data(TotalCost)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "\r\nselect \r\nCAST(ps.date AS TEXT),\r\nps.Totalcosts as Purple,\r\nys.Totalcosts as Yellow\r\nfrom (\r\nselect\r\n  date,\r\n  Totalcosts\r\nFROM\r\n  py_servcie\r\nwhere\r\n  source = 'yellow'\r\n) ys \r\ninner join \r\n\r\n(\r\nselect\r\n  date,\r\n  Totalcosts\r\nFROM\r\n  py_servcie\r\nwhere\r\n  source = 'purple'\r\n) ps\r\non ps.date=ys.date\r\nOrder \r\n by ps.date desc\r\nLimit 2"
    }
   ]
  },
  {
   "title": "Capabilites year wise",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "rawSql": "\r\nselect \r\nps.yearWise as yr,\r\nps.cp as purple_cp,\r\nys.cp as yellow_cp\r\nfrom (\r\nselect\r\n  DATE_PART('Year', date) AS yearWise,\r\n  sum(CapabilitiesService) as cp\r\nFROM\r\n  py_servcie\r\nwhere\r\n  source = 'yellow'\r\nGROUP BY\r\n  DATE_PART('Year', date)\r\n) ys \r\ninner join \r\n\r\n(\r\nselect\r\n  DATE_PART('Year', date) AS yearWise,\r\n  sum(CapabilitiesService) as cp\r\nFROM\r\n  py_servcie\r\nwhere\r\n  source = 'purple'\r\nGROUP BY\r\n  DATE_PART('Year', date)\r\n) ps\r\non ys.yearWise=ps.yearWise"
    }
   ]
  },
  {
   "title": "yellow_service_latest two_months_data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select\r\n  date  as \"time\",\r\n  CapabilitiesService,\r\n  Icapabilities,\r\n  APIService,\r\n  ExAPIService,\r\n\tPerformancesService,\r\n\tBCapabilitiesService,\r\n\tCCTVService,\r\n\tTotalcosts,\r\n\tIcapabilitiesService,\r\n\tNetService,\r\n\tAppService,\r\n\tYieldService\r\n\t\r\nFROM\r\n  py_servcie\r\nwhere\r\n  source = 'yellow'\r\nOrder \r\n by date desc\r\nLimit 2\r\n"
    }
   ]
  },
  {
   "title": "Capabilites MonthWise",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "\r\nselect \r\nCAST(ps.date AS TEXT),\r\nps.CapabilitiesService as purple_CapabilitiesService,\r\nys.CapabilitiesService as yellow_CapabilitiesService\r\nfrom (\r\nselect\r\n  date,\r\n  CapabilitiesService\r\nFROM\r\n  py_servcie\r\nwhere\r\n  source = 'yellow'\r\n) ys \r\ninner join \r\n\r\n(\r\nselect\r\n  date,\r\n  CapabilitiesService\r\nFROM\r\n  py_servcie\r\nwhere\r\n  source = 'purple'\r\n) ps\r\non ps.date=ys.date"
    }
   ]
  },
  {
   "title": "purple_service_latest two_months_data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select\r\n  date  as \"time\",\r\n  CapabilitiesService,\r\n  Icapabilities,\r\n  APIService,\r\n  ExAPIService,\r\n\tPerformancesService,\r\n\tBCapabilitiesService,\r\n\tCCTVService,\r\n\tTotalcosts,\r\n\tIcapabilitiesService,\r\n\tNetService,\r\n\tAppService,\r\n\tYieldService\r\n\t\r\nFROM\r\n  py_servcie\r\nwhere\r\n  source = 'purple'\r\nOrder \r\n by date desc\r\nLimit 2\r\n"
    }
   ]
  },
  {
   "title": "Recent Data(TotalCost)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "\r\nselect \r\nCAST(ps.date AS TEXT),\r\nps.Totalcosts as Purple,\r\nys.Totalcosts as Yellow\r\nfrom (\r\nselect\r\n  date,\r\n  Totalcosts\r\nFROM\r\n  py_servcie\r\nwhere\r\n  source = 'yellow'\r\n) ys \r\ninner join \r\n\r\n(\r\nselect\r\n  date,\r\n  Totalcosts\r\nFROM\r\n  py_servcie\r\nwhere\r\n  source = 'purple'\r\n) ps\r\non ps.date=ys.date\r\nOrder \r\n by ps.date desc\r\nLimit 2"
    }
   ]
  }
 ]
}